version: '2'
services:
  cryptoprice:
    image: lampsolutions/cryptoprice:0.1
    build: ./
    env_file:
      - .env
    restart: always
    ports:
      - 8080:80
  cryptoprice-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - mysqldb-vol-1:/var/lib/mysql

volumes:
  mysqldb-vol-1:
